name: Teste TodoList Fullstack

on:
  push:
    branches:
      - teste
  pull_request:
    branches:
      - teste

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      #1: pegar o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      #2: instalar Docker Compose
      - name: Instalar Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      #: subir containers
      - name: Subir containers
        run: docker-compose up -d --build

      #4: rodar testes automatizados
      - name: Rodar testes automatizados
        run: bash test.sh

      #5: parar containers
      - name: Parar containers
        run: docker-compose down